1:
  id: 'size'
  sign: +1
2:
  id: 'init_enhancement'
  sign: -1
3:
  id: 'smoothness'
  sign: -1
4:
  id: 'late_enhancement'
  sign: +1
5:
  id: 'CPE'
  sign: +1
6:
  id: 'sharpness_var'
  sign: -1
7:
  id: 'shape'
  sign: -1
8:
  id: 'sharpness_mean'
  sign: -1
